# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52582e1848fdd1397417298cd119f14a66b0365a24f9b52d70bdc81993a4fe1eaf8894ad9785334411094e2052293619edff15dc65257ba3b8564e63983b351b

test:
  secret_key_base: 890935d5235599fea6bd47d376c9c3aaedacb6547f68449fad9f7f453cb38d97fce7bc3bd143d2f84f4b1b5416c3e7b344384b7702909fd2a1c2f213816052a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
